name: escoumins
general_river_name: ESC

rgb_image_folder_path: "D:/SERIF/ESC/photos_crop/"
transect_path: "D:/SERIF/ESC/Transect_mathias_nov_2024/Transects_Level_2_ESC.shp"
shade_mask_path: "D:/SERIF/ESC/mask_hab_mathias_nov_2024/MASK_HAB_ESC.shp"
index_file_path: "D:/SERIF/ESC/PHOTOS/Index/Index_Ortho_utilises_ESC.shp"

cross_section_output_path: "D:/SERIF/ESC/HAB_2024/cross_section_points/"
trapezoid_output_path: "D:/SERIF/ESC/HAB_2024/trapezoid/"
hab_output_path: "D:/SERIF/ESC/HAB_2024/hab"
water_speed_output_path: "D:/SERIF/ESC/HAB_2024/vitesse/"
d84_output_path: "D:/SERIF/ESC/HAB_2024/d84/"
iqh_output_path: "D:/SERIF/ESC/HAB_2024/iqh/"
