name: petite_matane
general_river_name: MAN

rgb_image_folder_path: "D:/SERIF/MAN/photos_crop_petite_matane/"
transect_path: "D:/SERIF/MAN/Transect_mathias_nov_2024/Transects_Level_2_PMAN.shp"
shade_mask_path: "D:/SERIF/MAN/mask_hab_mathias_nov_2024/mask_ombres_reflets_PMAN.shp"
index_file_path: "D:/SERIF/MAN/PHOTOS/Index/Index_ortho_utilisees_PMAN.shp"

cross_section_output_path: "D:/SERIF/MAN/HAB_2024/Petite_MAN/cross_section_points/"
trapezoid_output_path: "D:/SERIF/MAN/HAB_2024/Petite_MAN/trapezoid/"
hab_output_path: "D:/SERIF/MAN/HAB_2024/Petite_MAN/hab/"
water_speed_output_path: "D:/SERIF/MAN/HAB_2024/Petite_MAN/vitesse/"
d84_output_path: "D:/SERIF/MAN/HAB_2024/Petite_MAN/d84/"
iqh_output_path: "D:/SERIF/MAN/HAB_2024/Petite_MAN/iqh/"
