name: st_jean
general_river_name: STJ

rgb_image_folder_path: "D:/SERIF/STJ/photos_crop/"
transect_path: "D:/SERIF/STJ/Transect_mathias_nov_2024/Transects_Level_2_STJ.shp"
shade_mask_path: "D:/SERIF/STJ/mask_hab_mathias_nov_2024/mask_ombres_reflets_STJ.shp"
index_file_path: "D:/SERIF/STJ/PHOTOS/Index/Index_Hierarchie_St-Jean_MTM5.shp"

cross_section_output_path: "D:/SERIF/STJ/HAB_2024/STJ/cross_section_points/"
trapezoid_output_path: "D:/SERIF/STJ/HAB_2024/STJ/trapezoid/"
hab_output_path: "D:/SERIF/STJ/HAB_2024/STJ/hab/"
water_speed_output_path: "D:/SERIF/STJ/HAB_2024/STJ/vitesse/"
d84_output_path: "D:/SERIF/STJ/HAB_2024/STJ/d84/"
iqh_output_path: "D:/SERIF/STJ/HAB_2024/STJ/iqh/"
