name: ste-marguerite
general_river_name: SMR

rgb_image_folder_path: "D:/SERIF/SMR/photos_crop/"
transect_path: "D:/SERIF/SMR/Transect_mathias_nov_2024/Transects_Level_2_SMR.shp"
shade_mask_path: "D:/SERIF/SMR/mask_hab_mathias_nov_2024/Mask_ombres_reflets_SMR.shp"
index_file_path: "D:/SERIF/SMR/PHOTOS/Index/Index_Ortho_Utilise_SMR_no_nir.shp"

cross_section_output_path: "D:/SERIF/SMR/HAB_2024/cross_section_points/"
trapezoid_output_path: "D:/SERIF/SMR/HAB_2024/trapezoid/"
hab_output_path: "D:/SERIF/SMR/HAB_2024/hab"
water_speed_output_path: "D:/SERIF/SMR/HAB_2024/vitesse/"
d84_output_path: "D:/SERIF/SMR/HAB_2024/d84/"
iqh_output_path: "D:/SERIF/SMR/HAB_2024/iqh/"
